import { addDoc, collection } from "firebase/firestore";
import { db } from "../firebase.service";

// const voices = [
//   {
//     songName: "Is This Love",
//     vid: "69RdQFDuYPI",
//     artistName: "Bob Marley",
//     voices: [
//       {
//         name: "Kanye West",
//         id: "Q3T1O4BBFonyBoyJo3Ms",
//         creatorName: "readi-playa",
//         creatorId: "LtFqRMsmMZvZdf2AIERu",
//         avatar: "8",
//       },
//       {
//         name: "Shawn Mendes",
//         id: "dX6aDQXhGjmV22PjAUrI",
//         creatorName: "samUrI",
//         creatorId: "GC7KjOf6BS913nZM8apb",
//         avatar: "7",
//       },
//     ],
//     img: "isthislove.jpg",
//     sections: [
//       { name: "Intro", start: 0 },
//       { name: "Verse", start: 16 },
//       { name: "Chorus", start: 55 },
//       { name: "Bridge", start: 71 },
//       { name: "Verse", start: 102 },
//       { name: "Chorus", start: 122 },
//       { name: "Bridge", start: 157 },
//       { name: "Verse", start: 187 },
//       { name: "Outro", start: 222 },
//     ],
//     bpm: 122,
//     views: 0,
//     duration: 234,
//   },
//   {
//     songName: "Baddadan",
//     vid: "rkjNL4dX-U4",
//     artistName: "Chase & Status",
//     voices: [
//       {
//         name: "Trump",
//         id: "trump",
//         creatorName: "AstralVisions",
//         creatorId: "38XkUcZIXTiJC51gjjzr",
//         avatar: "5",
//       },
//       {
//         name: "Cartman",
//         id: "cartman",
//         creatorName: "Emkatters",
//         creatorId: "LcCC807hUeGCLEV5Hscj",
//         avatar: "4",
//       },
//       {
//         name: "Biden",
//         id: "biden",
//         creatorName: "paradroid68",
//         creatorId: "4C8CrwUMB7k9Bst5FfWK",
//         avatar: "3",
//       },
//     ],
//     img: "baddadan.jpeg",
//     sections: [
//       { name: "Intro", start: 0 },
//       { name: "Verse", start: 22 },
//       { name: "Hook", start: 42 },
//       { name: "Verse", start: 64 },
//       { name: "Hook", start: 86 },
//       { name: "Verse", start: 108 },
//       { name: "Bridge", start: 131 },
//       { name: "Hook", start: 152 },
//       { name: "Drop", start: 173 },
//       { name: "Outro", start: 196 },
//     ],
//     bpm: 88,
//     views: 0,
//     duration: 220,
//   },
//   {
//     songName: "Gangsta's Paradise",
//     vid: "fPO76Jlnz6c",
//     artistName: "Coolio",
//     voices: [
//       {
//         name: "Cartman",
//         id: "cartman",
//         creatorName: "Emkatters",
//         creatorId: "LcCC807hUeGCLEV5Hscj",
//         avatar: "4",
//       },
//       {
//         name: "Mario",
//         id: "mario",
//         creatorName: "readi-playa",
//         creatorId: "LtFqRMsmMZvZdf2AIERu",
//         avatar: "8",
//       },
//       {
//         name: "Ed Sheeran",
//         id: "ed_sheeran",
//         creatorName: "Gr8Fairee",
//         creatorId: "Hq075VWWLYVjnWdLhfah",
//         avatar: "2",
//       },
//     ],
//     img: "gangsta.jpg",
//     sections: [
//       { name: "Intro", start: 0 },
//       { name: "Verse", start: 26 },
//       { name: "Chorus", start: 62 },
//       { name: "Verse", start: 86 },
//       { name: "hook", start: 121 },
//       { name: "chorus", start: 134 },
//       { name: "verse", start: 158 },
//       { name: "chorus", start: 182 },
//       { name: "hook", start: 205 },
//       { name: "outro", start: 230 },
//     ],
//     bpm: 80,
//     views: 0,
//     duration: 257,
//   },
//   {
//     songName: "Flowers",
//     vid: "G7KNmW9a75Y",
//     artistName: "Miley Cyrus",
//     voices: [
//       {
//         name: "Biden",
//         id: "biden",
//         creatorName: "Gr8Fairee",
//         creatorId: "Hq075VWWLYVjnWdLhfah",
//         avatar: "2",
//       },
//       {
//         name: "Billie Ellish",
//         id: "billie_ellish",
//         creatorName: "Pammy",
//         creatorId: "upsDmsN77H3AQgDBi3tQ",
//         avatar: "1",
//       },
//       {
//         name: "Cartman",
//         id: "cartman",
//         creatorName: "Emkatters",
//         creatorId: "LcCC807hUeGCLEV5Hscj",
//         avatar: "4",
//       },
//       {
//         name: "Trump",
//         id: "trump",
//         creatorName: "AstralVisions",
//         creatorId: "38XkUcZIXTiJC51gjjzr",
//         avatar: "5",
//       },
//     ],
//     img: "flowers.webp",
//     sections: [
//       { name: "Intro", start: 0 },
//       { name: "verse", start: 7 },
//       { name: "pre-chorus", start: 24 },
//       { name: "chorus", start: 33 },
//       { name: "post-chorus", start: 61 },
//       { name: "verse", start: 68 },
//       { name: "pre-chorus", start: 85 },
//       { name: "chorus", start: 94 },
//       { name: "post-chorus", start: 122 },
//       { name: "pre-chorus", start: 138 },
//       { name: "chorus", start: 147 },
//       { name: "post-chorus", start: 179 },
//       { name: "outro", start: 195 },
//     ],
//     bpm: 118,
//     views: 0,
//     duration: 202,
//   },
//   {
//     songName: "Smells Like Teen Spirit",
//     vid: "hTWKbfoikeg",
//     artistName: "Nirvana",
//     voices: [
//       {
//         name: "Cartman",
//         id: "cartman",
//         creatorName: "AstralVisions",
//         creatorId: "38XkUcZIXTiJC51gjjzr",
//         avatar: "5",
//       },
//       {
//         name: "Rihanna",
//         id: "rihanna",
//         creatorName: "Pammy",
//         creatorId: "upsDmsN77H3AQgDBi3tQ",
//         avatar: "1",
//       },
//     ],
//     img: "smells.jpeg",
//     sections: [
//       { name: "Intro", start: 0 },
//       { name: "verse", start: 18 },
//       { name: "pre-chorus", start: 43 },
//       { name: "chorus", start: 58 },
//       { name: "post-chorus", start: 82 },
//       { name: "verse", start: 92 },
//       { name: "pre-chorus", start: 117 },
//       { name: "chorus", start: 132 },
//       { name: "post-chorus", start: 156 },
//       { name: "bridge", start: 1666 },
//       { name: "verse", start: 182 },
//       { name: "pre-chorus", start: 207 },
//       { name: "chorus", start: 222 },
//       { name: "outro", start: 246 },
//     ],
//     bpm: 117,
//     views: 0,
//     duration: 278,
//   },
//   {
//     songName: "Only Girl In The World",
//     vid: "pa14VNsdSYM",
//     artistName: "Rihanna",
//     voices: [
//       {
//         name: "Cartman",
//         id: "cartman",
//         creatorName: "Gr8Fairee",
//         creatorId: "Hq075VWWLYVjnWdLhfah",
//         avatar: "2",
//       },
//       {
//         name: "Freddy Mercury",
//         id: "freddy",
//         creatorName: "Pammy",
//         creatorId: "upsDmsN77H3AQgDBi3tQ",
//         avatar: "1",
//       },
//     ],
//     img: "onlygirl.png",
//     sections: [
//       { name: "Intro", start: 0 },
//       { name: "verse", start: 31 },
//       { name: "chorus", start: 61 },
//       { name: "verse", start: 107 },
//       { name: "chorus", start: 137 },
//       { name: "bridge", start: 168 },
//       { name: "chorus", start: 182 },
//       { name: "outro", start: 235 },
//     ],
//     bpm: 126,
//     views: 0,
//     duration: 252,
//   },
//   {
//     songName: "Scream & Shout",
//     vid: "kYtGl1dX5qI",
//     artistName: "Will.i.am & Britney Spears",
//     voices: [
//       {
//         name: "Cartman",
//         id: "cartman",
//         creatorName: "samUrI",
//         creatorId: "GC7KjOf6BS913nZM8apb",
//         avatar: "7",
//       },
//       {
//         name: "Elon Musk",
//         id: "elonmusk",
//         creatorName: "Emkatters",
//         creatorId: "LcCC807hUeGCLEV5Hscj",
//         avatar: "4",
//       },
//     ],
//     img: "scream.png",
//     sections: [
//       { name: "Intro", start: 0 },
//       { name: "refrain", start: 14 },
//       { name: "pre-chorus", start: 29 },
//       { name: "chorus", start: 43 },
//       { name: "post-chorus", start: 69 },
//       { name: "drop", start: 74 },
//       { name: "verse", start: 87 },
//       { name: "refrain", start: 117 },
//       { name: "pre-chorus", start: 133 },
//       { name: "chorus", start: 147 },
//       { name: "post-chorus", start: 173 },
//       { name: "drop", start: 177 },
//       { name: "bridge", start: 191 },
//       { name: "chorus", start: 221 },
//       { name: "post-chorus", start: 261 },
//       { name: "outro", start: 266 },
//     ],
//     bpm: 130,
//     views: 0,
//     duration: 291,
//   },
//   {
//     songName: "Still D.R.E.",
//     vid: "Qeem6ZVr8Ic",
//     artistName: "Dr. Dre",
//     voices: [
//       {
//         name: "Homer Simpson",
//         id: "homer_simpson",
//         creatorName: "Emkatters",
//         creatorId: "LcCC807hUeGCLEV5Hscj",
//         avatar: "4",
//       },
//       {
//         name: "Drake",
//         id: "drake",
//         creatorName: "Gr8Fairee",
//         creatorId: "Hq075VWWLYVjnWdLhfah",
//         avatar: "2",
//       },
//       {
//         name: "Morgan Freeman",
//         id: "morgan_freeman",
//         creatorName: "readi-playa",
//         creatorId: "LtFqRMsmMZvZdf2AIERu",
//         avatar: "8",
//       },
//     ],
//     img: "drdre.jpeg",
//     sections: [
//       { name: "Intro", start: 0 },
//       { name: "verse", start: 20 },
//       { name: "chorus", start: 61 },
//       { name: "verse", start: 82 },
//       { name: "chorus", start: 123 },
//       { name: "verse", start: 144 },
//       { name: "chorus", start: 184 },
//       { name: "outro", start: 217 },
//     ],
//     bpm: 93,
//     views: 0,
//     duration: 290,
//   },
//   {
//     songName: "Rhythm Is a Dancer",
//     vid: "P-sGt5E2epc",
//     artistName: "SNAP!",
//     voices: [
//       {
//         name: "Rihanna",
//         id: "rihanna",
//         creatorName: "Pammy",
//         creatorId: "upsDmsN77H3AQgDBi3tQ",
//         avatar: "1",
//       },
//       {
//         name: "Cartman",
//         id: "cartman",
//         creatorName: "Emkatters",
//         creatorId: "LcCC807hUeGCLEV5Hscj",
//         avatar: "4",
//       },
//     ],
//     img: "rhythm.jpg",
//     sections: [
//       { name: "Intro", start: 0 },
//       { name: "chorus", start: 31 },
//       { name: "post-chorus", start: 46 },
//       { name: "chorus", start: 62 },
//       { name: "post-chorus", start: 77 },
//       { name: "chorus", start: 93 },
//       { name: "bridge", start: 109 },
//       { name: "verse", start: 124 },
//       { name: "chorus", start: 155 },
//       { name: "post-chorus", start: 170 },
//       { name: "bridge", start: 186 },
//       { name: "outro", start: 201 },
//     ],
//     duration: 223,
//     bpm: 290,
//     views: 0,
//   },
//   {
//     songName: "Duality",
//     vid: "B2lmOei7qfk",
//     artistName: "Slipknot",
//     voices: [
//       {
//         name: "Cartman",
//         id: "cartman",
//         creatorName: "AstralVisions",
//         creatorId: "38XkUcZIXTiJC51gjjzr",
//         avatar: "5",
//       },
//       {
//         name: "Terminator",
//         id: "terminator",
//         creatorName: "paradroid68",
//         creatorId: "4C8CrwUMB7k9Bst5FfWK",
//         avatar: "3",
//       },
//       {
//         name: "Arthur Morgan",
//         id: "arthur_morgan",
//         creatorName: "paradroid68",
//         creatorId: "4C8CrwUMB7k9Bst5FfWK",
//         avatar: "3",
//       },
//     ],
//     img: "duality.jpg",
//     sections: [
//       { name: "Intro", start: 0 },
//       { name: "verse", start: 31 },
//       { name: "verse", start: 57 },
//       { name: "chorus", start: 71 },
//       { name: "verse", start: 88 },
//       { name: "chorus", start: 107 },
//       { name: "bridge", start: 137 },
//       { name: "chorus", start: 167 },
//       { name: "outro", start: 202 },
//     ],
//     duration: 215,
//     bpm: 144,
//     views: 0,
//   },
// ];

const createVoiceDoc = async () => {
  // const col = collection(db, "covers");
  // voices.map((voice) => {
  //   addDoc(col, voice);
  // });
};

export { createVoiceDoc };
