import { addDoc, collection, doc } from "firebase/firestore";
import { db } from "../firebase.service";

const voices = [
  {
    songName: "Is This Love",
    vid: "69RdQFDuYPI",
    artistName: "Bob Marley",
    voices: [
      { name: "Kanye West", id: "Q3T1O4BBFonyBoyJo3Ms" },
      { name: "Shawn Mendes", id: "dX6aDQXhGjmV22PjAUrI" },
    ],
    img: "isthislove.jpg",
    createdInfo: { name: "Saulgoodman", id: "1", img: "1.webp" },
    sections: [
      { name: "Intro", start: 0 },
      { name: "Verse", start: 16 },
      { name: "Chorus", start: 55 },
      { name: "Bridge", start: 71 },
      { name: "Verse", start: 102 },
      { name: "Chorus", start: 122 },
      { name: "Bridge", start: 157 },
      { name: "Verse", start: 187 },
      { name: "Outro", start: 222 },
    ],
    bpm: 122,
    views: 47,
    duration: 234,
  },
  {
    songName: "Baddadan",
    vid: "rkjNL4dX-U4",
    artistName: "Chase & Status",
    voices: [
      { name: "Trump", id: "trump" },
      { name: "Cartman", id: "cartman" },
      { name: "Biden", id: "biden" },
    ],
    img: "baddadan.jpeg",
    createdInfo: { name: "Heisenberg", id: "2", img: "2.webp" },
    sections: [
      { name: "Intro", start: 0 },
      { name: "Verse", start: 22 },
      { name: "Hook", start: 42 },
      { name: "Verse", start: 64 },
      { name: "Hook", start: 86 },
      { name: "Verse", start: 108 },
      { name: "Bridge", start: 131 },
      { name: "Hook", start: 152 },
      { name: "Drop", start: 173 },
      { name: "Outro", start: 196 },
    ],
    bpm: 88,
    views: 93,
    duration: 220,
  },
  {
    songName: "Gangsta's Paradise",
    vid: "fPO76Jlnz6c",
    artistName: "Coolio",
    voices: [
      { name: "Cartman", id: "cartman" },
      { name: "Mario", id: "mario" },
      { name: "Ed Sheeran", id: "ed_sheeran" },
    ],
    img: "gangsta.jpg",
    createdInfo: { name: "Barry Allen", id: "3", img: "3.webp" },
    sections: [
      { name: "Intro", start: 0 },
      { name: "Verse", start: 26 },
      { name: "Chorus", start: 62 },
      { name: "Verse", start: 86 },
      { name: "hook", start: 121 },
      { name: "chorus", start: 134 },
      { name: "verse", start: 158 },
      { name: "chorus", start: 182 },
      { name: "hook", start: 205 },
      { name: "outro", start: 230 },
    ],
    bpm: 80,
    views: 105,
    duration: 257,
  },
  {
    songName: "Flowers",
    vid: "G7KNmW9a75Y",
    artistName: "Miley Cyrus",
    voices: [
      { name: "Biden", id: "biden" },
      { name: "Billie Ellish", id: "billie_ellish" },
      { name: "Cartman", id: "cartman" },
      { name: "Trump", id: "trump" },
    ],
    img: "flowers.webp",
    createdInfo: { name: "Lorem Ipsum", id: "4", img: "4.webp" },
    sections: [
      { name: "Intro", start: 0 },
      { name: "verse", start: 7 },
      { name: "pre-chorus", start: 24 },
      { name: "chorus", start: 33 },
      { name: "post-chorus", start: 61 },
      { name: "verse", start: 68 },
      { name: "pre-chorus", start: 85 },
      { name: "chorus", start: 94 },
      { name: "post-chorus", start: 122 },
      { name: "pre-chorus", start: 138 },
      { name: "chorus", start: 147 },
      { name: "post-chorus", start: 179 },
      { name: "outro", start: 195 },
    ],
    bpm: 118,
    views: 32,
    duration: 202,
  },
  {
    songName: "Smells Like Teen Spirit",
    vid: "hTWKbfoikeg",
    artistName: "Nirvana",
    voices: [
      { name: "Cartman", id: "cartman" },
      { name: "Rihanna", id: "rihanna" },
    ],
    img: "smells.jpeg",
    createdInfo: { name: "Ghost", id: "5", img: "5.webp" },
    sections: [
      { name: "Intro", start: 0 },
      { name: "verse", start: 18 },
      { name: "pre-chorus", start: 43 },
      { name: "chorus", start: 58 },
      { name: "post-chorus", start: 82 },
      { name: "verse", start: 92 },
      { name: "pre-chorus", start: 117 },
      { name: "chorus", start: 132 },
      { name: "post-chorus", start: 156 },
      { name: "bridge", start: 1666 },
      { name: "verse", start: 182 },
      { name: "pre-chorus", start: 207 },
      { name: "chorus", start: 222 },
      { name: "outro", start: 246 },
    ],
    bpm: 117,
    views: 45,
    duration: 278,
  },
  {
    songName: "Only Girl In The World",
    vid: "pa14VNsdSYM",
    artistName: "Rihanna",
    voices: [
      { name: "Cartman", id: "cartman" },
      { name: "Freddy Mercury", id: "freddy" },
    ],
    img: "onlygirl.png",
    createdInfo: { name: "Test", id: "6", img: "6.webp" },
    sections: [
      { name: "Intro", start: 0 },
      { name: "verse", start: 31 },
      { name: "chorus", start: 61 },
      { name: "verse", start: 107 },
      { name: "chorus", start: 137 },
      { name: "bridge", start: 168 },
      { name: "chorus", start: 182 },
      { name: "outro", start: 235 },
    ],
    bpm: 126,
    views: 77,
    duration: 252,
  },
  {
    songName: "Scream & Shout",
    vid: "kYtGl1dX5qI",
    artistName: "Will.i.am & Britney Spears",
    voices: [
      { name: "Cartman", id: "cartman" },
      { name: "Elon Musk", id: "elonmusk" },
    ],
    img: "scream.png",
    createdInfo: { name: "Adam", id: "7", img: "7.webp" },
    sections: [
      { name: "Intro", start: 0 },
      { name: "refrain", start: 14 },
      { name: "pre-chorus", start: 29 },
      { name: "chorus", start: 43 },
      { name: "post-chorus", start: 69 },
      { name: "drop", start: 74 },
      { name: "verse", start: 87 },
      { name: "refrain", start: 117 },
      { name: "pre-chorus", start: 133 },
      { name: "chorus", start: 147 },
      { name: "post-chorus", start: 173 },
      { name: "drop", start: 177 },
      { name: "bridge", start: 191 },
      { name: "chorus", start: 221 },
      { name: "post-chorus", start: 261 },
      { name: "outro", start: 266 },
    ],
    bpm: 130,
    views: 92,
    duration: 291,
  },
  {
    songName: "Still D.R.E.",
    vid: "Qeem6ZVr8Ic",
    artistName: "Dr. Dre",
    voices: [
      { name: "Homer Simpson", id: "homer_simpson" },
      { name: "Drake", id: "drake" },
      { name: "Morgan Freeman", id: "morgan_freeman" },
    ],
    img: "drdre.jpeg",
    createdInfo: { name: "Saulgoodman", id: "8", img: "8.webp" },
    sections: [
      { name: "Intro", start: 0 },
      { name: "verse", start: 20 },
      { name: "chorus", start: 61 },
      { name: "verse", start: 82 },
      { name: "chorus", start: 123 },
      { name: "verse", start: 144 },
      { name: "chorus", start: 184 },
      { name: "outro", start: 217 },
    ],
    bpm: 93,
    views: 112,
    duration: 290,
  },
  {
    songName: "Rhythm Is a Dancer",
    vid: "P-sGt5E2epc",
    artistName: "SNAP!",
    voices: [
      { name: "Rihanna", id: "rihanna" },
      { name: "Cartman", id: "cartman" },
    ],
    img: "rhythm.jpg",
    createdInfo: { name: "CryptoKid", id: "3", img: "1.webp" },
    sections: [
      { name: "Intro", start: 0 },
      { name: "chorus", start: 31 },
      { name: "post-chorus", start: 46 },
      { name: "chorus", start: 62 },
      { name: "post-chorus", start: 77 },
      { name: "chorus", start: 93 },
      { name: "bridge", start: 109 },
      { name: "verse", start: 124 },
      { name: "chorus", start: 155 },
      { name: "post-chorus", start: 170 },
      { name: "bridge", start: 186 },
      { name: "outro", start: 201 },
    ],
    duration: 223,
    bpm: 290,
    views: 66,
  },
  {
    songName: "Duality",
    vid: "B2lmOei7qfk",
    artistName: "Slipknot",
    voices: [
      { name: "Cartman", id: "cartman" },
      { name: "Terminator", id: "terminator" },
      { name: "Arthur Morgan", id: "arthur_morgan" },
    ],
    img: "duality.jpg",
    createdInfo: { name: "Adam", id: "7", img: "1.webp" },
    sections: [
      { name: "Intro", start: 0 },
      { name: "verse", start: 31 },
      { name: "verse", start: 57 },
      { name: "chorus", start: 71 },
      { name: "verse", start: 88 },
      { name: "chorus", start: 107 },
      { name: "bridge", start: 137 },
      { name: "chorus", start: 167 },
      { name: "outro", start: 202 },
    ],
    duration: 215,
    bpm: 144,
    views: 64,
  },
];

const createVoiceDoc = async () => {
  const col = collection(db, "voices");
  voices.map((voice) => {
    addDoc(col, voice);
  });
};

export { createVoiceDoc };
